### ISSUE TITLE
Test commons

### ISSUE THREAD

**Issue by mrjosch** [jtdLab/DartCounterPlayAPI#23]
Implement classes:

PacketContainerDeserializerTest.java
PacketTypeSerializerTest.java
JsonValidatorTest.java
JsonManagerTest.java

**Comment by jtdLab** [comment]
JsonValidatorTest: testIsPerformThrowPacketValid() todo

**Comment by jtdLab** [comment]
JsonValidatorTest: testIsPacketContainerValid() todo

**Comment by mrjosch** [comment]
JsonManagerTest.java testGson() todo
